ip: localhost
server:
  port: 9020

spring:
  datasource: # 数据库配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:    #你本地的数据库用户名
    password:  #你本地的数据库密码
    url: jdbc:mysql://${ip}:3306/xm_secondhand_manager?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  redis: # redis配置
    host: ${ip}
    port: 6379
    database: 0
  # rabbitmq: # RabbitMQ配置
  #   host:  # RabbitMQ服务器地址
  #   port: 5672 # RabbitMQ服务器端口
  #   username:  # RabbitMQ用户名
  #   password:  # RabbitMQ密码
  #   virtual-host: /second # RabbitMQ虚拟主机
  servlet: # 文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# AliOss配置


# 支付宝沙箱支付
